version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://visitor_app:visitor_password@db:5432/visitor_tracking
      - SESSION_SECRET=${SESSION_SECRET}
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=visitor_app
      - POSTGRES_PASSWORD=visitor_password
      - POSTGRES_DB=visitor_tracking
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init.js:/docker-entrypoint-initdb.d/db-init.js
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
