version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: besucherdaten
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_URL: postgres://postgres:postgres@db:5432/besucherdaten
      COOKIE_SECURE: 'false'
    ports:
      - "5050:5000"
    restart: unless-stopped
    command: ["npm", "run", "start"]

volumes:
  db-data: 